In [265]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [266]:
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 500)

In [267]:
data = pd.read_csv('../../Downloads/dobrano_.csv', header=0, sep=';', low_memory=False, encoding='latin1')
data.shape

(1581645, 86)

In [268]:
data.head()

,contador,ORIGEM,TIPOBITO,DTOBITO,HORAOBITO,NATURAL,CODMUNNATU,DTNASC,IDADE,SEXO,RACACOR,ESTCIV,ESC,ESC2010,SERIESCFAL,OCUP,CODMUNRES,LOCOCOR,CODESTAB,CODMUNOCOR,IDADEMAE,ESCMAE,ESCMAE2010,SERIESCMAE,OCUPMAE,QTDFILVIVO,QTDFILMORT,GRAVIDEZ,SEMAGESTAC,GESTACAO,PARTO,OBITOPARTO,PESO,TPMORTEOCO,OBITOGRAV,OBITOPUERP,ASSISTMED,EXAME,CIRURGIA,NECROPSIA,LINHAA,LINHAB,LINHAC,LINHAD,LINHAII,CAUSABAS,CB_PRE,COMUNSVOIM,DTATESTADO,CIRCOBITO,ACIDTRAB,FONTE,NUMEROLOTE,DTINVESTIG,DTCADASTRO,ATESTANTE,STCODIFICA,CODIFICADO,VERSAOSIST,VERSAOSCB,FONTEINV,DTRECEBIM,ATESTADO,DTRECORIGA,OPOR_DO,CAUSAMAT,ESCMAEAGR1,ESCFALAGR1,STDOEPIDEM,STDONOVA,DIFDATA,NUDIASOBCO,DTCADINV,TPOBITOCOR,DTCONINV,FONTES,TPRESGINFO,TPNIVELINV,DTCADINF,MORTEPARTO,DTCONCASO,ALTCAUSA,CAUSABAS_O,TPPOS,TP_ALTERA,CB_ALT
0,1,1,2,25012020,421.0,831.0,310160.0,10051951.0,468.0,1,1.0,4.0,2.0,1.0,3.0,999993.0,316930,3,NaN,316930,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,*R99X,NaN,NaN,NaN,NaN,R99,NaN,316930.0,25012020.0,NaN,NaN,NaN,20200003.0,NaN,3022020.0,3.0,S,S,3.2.02,3.2,NaN,12022020.0,R99,12022020,18,NaN,NaN,1.0,0.0,1,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R99,N,NaN,NaN
1,2,1,2,25012020,1910.0,831.0,316930.0,16031966.0,453.0,1,2.0,1.0,2.0,1.0,1.0,621005.0,316930,3,NaN,316930,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,*R99X,NaN,NaN,NaN,NaN,R99,NaN,316930.0,25012020.0,NaN,NaN,NaN,20200003.0,NaN,3022020.0,3.0,S,S,3.2.02,3.2,NaN,12022020.0,R99,12022020,18,NaN,NaN,1.0,0.0,1,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R99,N,NaN,NaN
2,3,1,2,14012020,1727.0,835.0,351360.0,10071937.0,482.0,2,1.0,2.0,2.0,1.0,1.0,999992.0,316930,1,2760657.0,316930,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,*J960,*R571,*K922,NaN,*K579*E46X,K579,NaN,NaN,14012020.0,NaN,NaN,NaN,20200003.0,NaN,3022020.0,1.0,S,S,3.2.02,3.2,NaN,12022020.0,J960/R571/K922*K579 E46,12022020,29,NaN,NaN,1.0,0.0,1,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,K579,N,NaN,NaN
3,4,1,2,20012020,1930.0,831.0,313870.0,2111946.0,473.0,2,1.0,4.0,2.0,1.0,3.0,999992.0,316080,1,2760657.0,316930,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,2.0,*J960,NaN,NaN,NaN,NaN,J960,NaN,316930.0,20012020.0,NaN,NaN,NaN,20200003.0,NaN,3022020.0,3.0,S,S,3.2.02,3.2,NaN,12022020.0,J960,12022020,23,NaN,NaN,1.0,0.0,1,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J960,N,NaN,NaN
4,5,1,2,26012020,2230.0,831.0,311090.0,12091959.0,460.0,1,1.0,1.0,5.0,5.0,NaN,231205.0,311390,1,2760657.0,316930,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,2.0,*J960,*A419,NaN,NaN,NaN,A419,NaN,316930.0,26012020.0,NaN,NaN,NaN,20200003.0,NaN,3022020.0,3.0,S,S,3.2.02,3.2,NaN,12022020.0,J960/A419,12022020,17,NaN,NaN,8.0,0.0,1,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A419,N,NaN,NaN

In [269]:
t = data.loc[data.GRAVIDEZ.notnull()]
t['GRAVIDEZ']

9          1.0
25         1.0
26         1.0
28         1.0
29         1.0
          ...
1581614    1.0
1581617    1.0
1581621    1.0
1581627    1.0
1581630    1.0
Name: GRAVIDEZ, Length: 57286, dtype: float64

In [270]:
data.describe()
# data.head()

,contador,ORIGEM,TIPOBITO,DTOBITO,HORAOBITO,NATURAL,CODMUNNATU,DTNASC,IDADE,SEXO,RACACOR,ESTCIV,ESC,ESC2010,SERIESCFAL,OCUP,CODMUNRES,LOCOCOR,CODESTAB,CODMUNOCOR,IDADEMAE,ESCMAE,ESCMAE2010,SERIESCMAE,OCUPMAE,QTDFILVIVO,QTDFILMORT,GRAVIDEZ,SEMAGESTAC,GESTACAO,PARTO,OBITOPARTO,PESO,TPMORTEOCO,OBITOGRAV,OBITOPUERP,ASSISTMED,EXAME,CIRURGIA,NECROPSIA,CB_PRE,COMUNSVOIM,DTATESTADO,CIRCOBITO,ACIDTRAB,FONTE,NUMEROLOTE,DTINVESTIG,DTCADASTRO,ATESTANTE,VERSAOSCB,FONTEINV,DTRECEBIM,DTRECORIGA,OPOR_DO,ESCMAEAGR1,ESCFALAGR1,STDOEPIDEM,STDONOVA,DIFDATA,NUDIASOBCO,DTCADINV,TPOBITOCOR,DTCONINV,TPRESGINFO,DTCADINF,MORTEPARTO,DTCONCASO,ALTCAUSA,TP_ALTERA
count,1.581645e+06,1.581645e+06,1.581645e+06,1.581645e+06,1.521078e+06,1.490323e+06,1.468002e+06,1.548913e+06,1.552740e+06,1.581645e+06,1.511625e+06,1.471715e+06,1.438406e+06,1.433667e+06,359251.000000,1.300832e+06,1.581645e+06,1.581645e+06,1.157136e+06,1.581645e+06,55092.000000,54134.000000,53944.000000,20348.000000,47968.000000,55090.000000,53413.000000,57286.000000,54668.000000,54785.000000,57051.000000,56617.000000,55239.000000,92730.000000,92954.000000,92943.000000,1.077714e+06,2176.000000,2123.000000,1.095815e+06,0.0,223249.000000,1.571512e+06,144010.000000,42859.000000,112337.000000,1.581483e+06,2.737510e+05,1.579153e+06,1.437280e+06,1.515467e+06,278440.000000,1.494909e+06,1.581645e+06,1.581645e+06,53944.000000,1.433667e+06,1.581641e+06,1.581645e+06,1.581645e+06,57825.000000,5.820600e+04,58206.000000,5.776000e+04,3496.000000,4.491800e+04,44918.000000,4.149600e+04,43756.000000,21149.000000
mean,7.908230e+05,1.001587e+00,1.981725e+00,1.581028e+07,1.205621e+03,8.243749e+02,3.161550e+05,1.541425e+07,4.629641e+02,1.437443e+00,2.309674e+00,2.570210e+00,3.509296e+00,2.533826e+00,4.313029,7.821881e+05,3.260919e+05,1.696474e+00,3.275607e+06,3.262121e+05,27.431242,4.205176,3.297253,4.252162,770740.742057,2.289998,1.797952,1.138411,31.726293,3.469271,1.495364,2.201017,1759.556038,8.031133,3.208748,4.010350,1.763451e+00,3.367188,3.341498,2.155591e+00,NaN,325975.319939,1.583187e+07,3.360003,4.081943,2.247826,2.020264e+07,1.567060e+07,1.572807e+07,2.713361e+00,3.269963e+00,4.656508,1.587042e+07,1.609554e+07,2.962505e+01,7.738877,6.610409e+00,2.023215e-05,9.998495e-01,7.018711e+01,78.793913,1.590641e+07,8.762636,1.566972e+07,1.387014,1.563618e+07,2.314551,1.573835e+07,1.794908,8.483285
std,4.565817e+05,3.980500e-02,1.339451e-01,8.817900e+06,6.731222e+02,7.087084e+01,8.387389e+04,8.714612e+06,4.840320e+01,4.980062e-01,1.428698e+00,1.777828e+00,2.355239e+00,2.735548e+00,1.877193,2.680159e+05,8.917194e+04,1.102637e+00,2.291750e+06,8.915085e+04,7.865407,1.751118,2.110716,2.293233,284685.296842,9.354023,11.355986,0.736504,11.810951,1.501499,0.926062,1.434484,1099.638246,0.951300,2.661106,2.304437,2.128541e+00,2.884889,2.780318,1.459130e+00,NaN,94144.391694,8.817509e+06,2.958886,3.283309,2.405422,4.373237e+03,8.770779e+06,8.705404e+06,1.618008e+00,5.125085e-02,2.209646,8.585735e+06,8.610001e+06,3.610169e+01,3.453784,4.371968e+00,4.497972e-03,1.226596e-02,9.442599e+01,72.522786,8.691534e+06,1.001902,8.712799e+06,0.656293,8.733459e+06,1.552222,8.790641e+06,0.403773,2.162114
min,1.000000e+00,1.000000e+00,1.000000e+00,1.012020e+06,0.000000e+00,4.000000e+00,1.100000e+05,1.011905e+06,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000,1.010500e+04,1.100000e+05,1.000000e+00,1.000000e+00,1.100010e+05,8.000000,1.000000,0.000000,1.000000,20305.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000e+00,1.000000,1.000000,1.000000e+00,NaN,110002.000000,1.012020e+06,1.000000,1.000000,1.000000,2.019001e+07,1.012020e+06,1.012002e+06,1.000000e+00,2.200000e+00,1.000000,1.022021e+06,1.022021e+06,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,1.012021e+06,1.000000,1.012020e+06,1.000000,1.012021e+06,1.000000,1.012021e+06,1.000000,2.000000
25%,3.954120e+05,1.000000e+00,2.000000e+00,8.082020e+06,6.350000e+02,8.260000e+02,2.608400e+05,8.051968e+06,4.560000e+02,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,1.000000e+00,3.000000,6.210050e+05,2.704300e+05,1.000000e+00,2.097613e+06,2.704300e+05,21.000000,3.000000,2.000000,3.000000,516120.000000,0.000000,0.000000,1.000000,26.000000,2.000000,1.000000,1.000000,765.000000,8.000000,2.000000,3.000000,1.000000e+00,2.000000,2.000000,2.000000e+00,NaN,261160.000000,8.082020e+06,1.000000,2.000000,1.000000,2.020002e+07,8.082020e+06,8.072020e+06,1.000000e+00,3.200000e+00,3.000000,8.092020e+06,9.072020e+06,1.000000e+01,5.000000,2.000000e+00,0.000000e+00,1.000000e+00,1.400000e+01,28.000000,8.122020e+06,9.000000,8.092020e+06,1.000000,8.072020e+06,1.000000,8.072020e+06,2.000000,9.000000
50%,7.908230e+05,1.000000e+00,2.000000e+00,1.603202e+07,1.210000e+03,8.310000e+02,3.144800e+05,1.508194e+07,4.700000e+02,1.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,1.000000e+00,4.000000,9.999910e+05,3.304110e+05,1.000000e+00,2.458888e+06,3.304550e+05,27.000000,4.000000,3.000000,3.000000,999991.000000,1.000000,0.000000,1.000000,32.000000,4.000000,1.000000,3.000000,1544.000000,8.000000,2.000000,3.000000,1.000000e+00,2.000000,2.000000,2.000000e+00,NaN,330100.000000,1.604202e+07,3.000000,2.000000,1.000000,2.020005e+07,1.602202e+07,1.512202e+07,2.000000e+00,3.300000e+00,4.000000,1.605202e+07,1.606202e+07,1.900000e+01,8.000000,9.000000e+00,0.000000e+00,1.000000e+00,3.100000e+01,58.000000,1.607202e+07,9.000000,1.602202e+07,1.000000,1.602202e+07,3.000000,1.603202e+07,2.000000,9.000000
75%,1.186234e+06,1.000000e+00,2.000000e+00,2.311202e+07,1.800000e+03,8.350000e+02,3.548500e+05,2.304195e+07,4.820000e+02,2.000000e+00,4.000000e+00,3.000000e+00,4.000000e+00,3.000000e+00,4.000000,9.999930e+05,3.550300e+05,3.000000e+00,3.285391e+06,3.550300e+05,33.000000,4.000000,3.000000,6.000000,999992.000000,2.000000,1.000000,1.000000,37.000000,5.000000,2.000000,3.000000,2650.000000,8.000000,2.000000,3.000000,1.000000e+00,2.000000,2.000000,2.000000e+00,NaN,355030.000000,2.311202e+07,3.000000,9.000000,2.000000,2.021000e+07,2.307202e+07,2.307202e+07,5.000000e+00,3.300000e+00,7.000000,2.309202e+07,2.310202e+07,3.600000e+01,11.000000,1.000000e+01,0.000000e+00,1.000000e+00,7.700000e+01,108.000000,2.310202e+07,9.000000,2.307202e+07,2.000000,2.309202e+07,3.000000,2.309202e+07,2.000000,9.000000
max,1.581645e+06,2.000000e+00,2.000000e+00,3.112202e+07,1.754100e+04,9.990000e+02,5.300100e+05,3.112202e+07,9.990000e+02,2.000000e+00,5.000000e+00,9.000000e+00,9.000000e+00,9.000000e+00,8.000000,9.999950e+05,5.300100e+05,9.000000e+00,9.999999e+06,5.300100e+05,99.000000,9.000000,9.000000,8.000000,999994.000000,99.000000,99.000000,9.000000,99.000000,9.000000,9.000000,9.000000,6770.000000,9.000000,9.000000,9.000000,9.000000e+00,9.000000,9.000000,9.000000e+00,NaN,539904.000000,3.112202e+07,9.000000,9.000000,9.000000,2.021034e+07,3.112202e+07,3.112202e+07,5.000000e+00,3.400000e+00,9.000000,3.112202e+07,3.112202e+07,5.340000e+02,12.000000,1.200000e+01,1.000000e+00,1.000000e+00,5.420000e+02,541.000000,3.112202e+07,9.000000,3.112202e+07,3.000000,3.112202e+07,9.000000,3.112202e+07,2.000000,16.000000

In [271]:
data.CAUSABAS.str[:3] == 'R99'

0           True
1           True
2          False
3          False
4          False
           ...
1581640    False
1581641     True
1581642    False
1581643    False
1581644    False
Name: CAUSABAS, Length: 1581645, dtype: bool

In [325]:
data.columns

Index(['contador', 'ORIGEM', 'TIPOBITO', 'DTOBITO', 'HORAOBITO', 'NATURAL',
       'CODMUNNATU', 'DTNASC', 'IDADE', 'SEXO', 'RACACOR', 'ESTCIV', 'ESC',
       'ESC2010', 'SERIESCFAL', 'OCUP', 'CODMUNRES', 'LOCOCOR', 'CODESTAB',
       'CODMUNOCOR', 'IDADEMAE', 'ESCMAE', 'ESCMAE2010', 'SERIESCMAE',
       'OCUPMAE', 'QTDFILVIVO', 'QTDFILMORT', 'GRAVIDEZ', 'SEMAGESTAC',
       'GESTACAO', 'PARTO', 'OBITOPARTO', 'PESO', 'TPMORTEOCO', 'OBITOGRAV',
       'OBITOPUERP', 'ASSISTMED', 'EXAME', 'CIRURGIA', 'NECROPSIA', 'LINHAA',
       'LINHAB', 'LINHAC', 'LINHAD', 'LINHAII', 'CAUSABAS', 'CB_PRE',
       'COMUNSVOIM', 'DTATESTADO', 'CIRCOBITO', 'ACIDTRAB', 'FONTE',
       'NUMEROLOTE', 'DTINVESTIG', 'DTCADASTRO', 'ATESTANTE', 'STCODIFICA',
       'CODIFICADO', 'VERSAOSIST', 'VERSAOSCB', 'FONTEINV', 'DTRECEBIM',
       'ATESTADO', 'DTRECORIGA', 'OPOR_DO', 'CAUSAMAT', 'ESCMAEAGR1',
       'ESCFALAGR1', 'STDOEPIDEM', 'STDONOVA', 'DIFDATA', 'NUDIASOBCO',
       'DTCADINV', 'TPOBITOCOR', 'DTCONINV', 'FONTES', 'TPRESGINFO',
       'TPNIVELINV', 'DTCADINF', 'MORTEPARTO', 'DTCONCASO', 'ALTCAUSA',
       'CAUSABAS_O', 'TPPOS', 'TP_ALTERA', 'CB_ALT'],
      dtype='object')

In [326]:
limit = data.shape[0]
df = data[:limit]
# deletando colunas:
# contador, pois já há o index das linhas do dataframe
# CODINST: Código da instalação da geração dos registros
# NUMERODV: número do dígito verificador (??)
# HORAOBITO: hora de óbito 
# NUMSUS: número da carteira do sus
# CODESTAB: código do estabelecimento
# NUMERODN: número da declaração de nascimento
# CRM: código de registro de médico, não precisaremos predizer
# data do atestado de óbito
# número do lote
# data do cadastro
# Indica se o mé
# dico que assina atendeu o paciente
# Status de instalação: se codificadora
# se está codificado ou não

## PREPROCESSAMENTO DO DATASET

In [327]:
def ajeitando_idades(df):
    idades = pd.DataFrame(df['IDADE']).astype('int')
#     print(idades.head())
    idades['ANOS_IDADE'] = pd.Series()
    
    idades.loc[idades['IDADE'] < 400, ['ANOS_IDADE']] = 0
    
    idades.loc[idades['IDADE'] > 400, ['ANOS_IDADE']] = (idades['IDADE'] - 400)
        
#     df.loc[(((df['IDADE'].str.len() == 3) & (df['IDADE'].str[0] != '4') & (df['IDADE'].str[0] != '5')) 
#             | df['IDADE'].str.len() < 3),
#            ['ANOS_IDADE']] = '0'
    
#     df.loc[((df['IDADE'].str.len() == 3) & (df['IDADE'].str[0] == '4') 
#             | (df['IDADE'].str[0] == '5')), 
#            ['ANOS_IDADE']] = str(int(df['IDADE'].str[0]) - 4) + df['IDADE'].str[1:]
    
#     df.loc[((df['IDADE'].str.len() == 3) & (df['IDADE'].str[0] == '4') 
#             | (df['IDADE'].str[0] == '5')), 
#            ['ANOS_IDADE']] = df['IDADE'].str[1:]
    
#     df['ANOS_IDADE'] = df['ANOS_IDADE'].astype('int')
#     print(idades['ANOS_IDADE'])
    
    return idades['ANOS_IDADE']

In [328]:
def faixa_etaria(df):
    faixas_etarias = np.arange(0, df.IDADE.max()+1, 5, dtype='int')
    df['FAIXA_ETARIA'] = pd.cut(df['IDADE'], faixas_etarias)
#     print(df.head(8))
#     faixas = df.groupby('FAIXA_ETARIA')
#     print(faixas.head())
#     print(df.groupby('FAIXA_ETARIA'))
# #     df['FAIXA_ETARIA'] = df.groupby('FAIXA_ETARIA')
#     return df['FAIXA_ETARIA']

In [329]:
def add_zero(row, name):
    if len(row[name]) < 8:
        row[name] = '0' + row[name]

In [330]:
def clean_date(df, name_column):
    dt_nasc = pd.DataFrame(df[name_column])
    
    dt_nasc[name_column] = dt_nasc[name_column].fillna(0)
    dt_nasc[name_column] = dt_nasc[name_column].astype('int')
    dt_nasc[name_column] = dt_nasc[name_column].astype('str')
    

    dt_nasc.apply(add_zero, name=name_column, axis='columns')
    dt_nasc[name_column] = dt_nasc[name_column].str.slice(0, 8)
    
    
    dt_nasc['ANO'] = dt_nasc[name_column].str[4:]

    dt_nasc['MES'] = dt_nasc[name_column].str.slice(2, 4)

    dt_nasc['DIA'] = dt_nasc[name_column].str.slice(0, 2)
    

    return dt_nasc

In [331]:
def codigos(row):
    if len(row['CODMUNOCOR']) < 7:
#         print('0' + row.DTOBITO[0])
        row['COD'] = row.CODMUNOCOR[:2]

In [332]:
def clean_states(df):
    data_estados = pd.read_csv('../../Downloads/estados_ibge.csv', sep=';', header=0, encoding='latin1')

    cod = pd.Series(data_estados['CODIGO'].astype('str'))
    cod = cod.values

    uf = pd.Series(data_estados['UF'].astype('str'))
    uf = uf.values

    cod_mun = pd.DataFrame(df.CODMUNOCOR.astype('str'))

    cod_mun['CODMUNOCOR'] = cod_mun.CODMUNOCOR.astype('str')
    cod_mun['CODMUNOCOR'].str.slice(0,2)
    cod_mun['COD'] = ""
    cod_mun.apply(codigos, axis='columns')
    cod_mun['ESTADO'] = cod_mun['COD'].replace(cod, uf)

    return cod_mun['ESTADO'], cod_mun['COD']

In [333]:
def separando(row):
    row['LETRA_INICIO'] = row.CATINIC[0]
    row['LETRA_FIM'] = row.CATFIM[0]
    row['NUM_INICIO'] = row.CATINIC[1:]
    row['NUM_FIM'] = row.CATFIM[1:]
#     print(row)

In [334]:
def limpeza(row, col_cids):
    for c in col_cids:
        if row[c].find('*') != -1:
            row[c] = row[c][1:]

In [335]:
def capitulo_cid(row, cids):
    cids.loc[((cids.CAUSABAS.str[0] == row.CATINIC[0]) | (cids.CAUSABAS.str[0] == row.CATFIM[0])) 
             & ((cids.CAUSABAS.str[1:] >= row.CATINIC[1:]) & (cids.CAUSABAS.str[1:] <= row.CATFIM[1:])),
             ['CAPITULO_CAUSA_BASICA', 'COD_CAPITULO_CAUSA_BASICA']] = [row.DESCRABREV, row.NUMCAP]

In [336]:
#grupo CID
def agrupamento_cid(row, cids):
    cids.loc[((cids.CAUSABAS.str[0] == row.CATINIC[0]) | (cids.CAUSABAS.str[0] == row.CATFIM[0])) 
             & ((cids.CAUSABAS.str[1:] >= row.CATINIC[1:]) & (cids.CAUSABAS.str[1:] <= row.CATFIM[1:])),
             ['COD_GRUPO_CAUSA_BASICA', 'GRUPO_CAUSA_BASICA']] = [row.CATINIC + '-' + row.CATFIM , row.DESCRICAO]

In [337]:
#CATEGORIA CID
#(cids.CAUSABAS.str.len() == 3) &
def categoria_cid(row, cids):
    cids.loc[((cids.CAUSABAS.str[:3] == row.CAT)),
             ['COD_CAUSA_BASICA', 'CAUSA_BASICA']] = [row.CAT, row.DESCRICAO]

In [338]:
#SUBCATEGORIA CID 
def sub_categoria_cid(row, cids):
    cids.loc[((cids.CAUSABAS.str.len() == 4) & (cids.CAUSABAS == row.SUBCAT)),
            ['CAUSA_BASICA']] = row.DESCRABREV[:6]

In [339]:
def nomeando_cids(df):

    df_cid_grupos = pd.read_csv('../../CID-10-GRUPOS.csv', header=0, sep=';', encoding='latin1')
    df_cid_grupos.head()

    df_cid_grupos = df_cid_grupos.drop(columns=['Unnamed: 0'])


    df_cid_cate = pd.read_csv('../../CID-10-CATEGORIAS.csv', header=0, sep=';', encoding='latin1')

    df_cid_sub = pd.read_csv('../../Downloads/CID-10-SUBCATEGORIAS.csv', header=0, sep=';', encoding='latin1')
    
    df_cid_cap = pd.read_csv('../../Downloads/CID-10-CAPITULOS.csv', header=0, sep=';', encoding='latin1')

    df_cid_cap['LETRA_INICIO'] = ""
    df_cid_cap['NUM_INICIO'] = ""
    df_cid_cap['LETRA_FIM'] = ""
    df_cid_cap['NUM_FIM'] = ""
    
    df_cid_grupos['LETRA_INICIO'] = ""
    df_cid_grupos['NUM_INICIO'] = ""
    df_cid_grupos['LETRA_FIM'] = ""
    df_cid_grupos['NUM_FIM'] = ""
    
    col_cids = ['CAUSABAS']

    cids = pd.DataFrame(df[col_cids].astype('str'))

#### RETIRANDO O '*' INÍCIO
    cids.apply(limpeza, col_cids=col_cids, axis='columns')

    cids['GRUPO_CAUSA_BASICA'] = ""
    cids['COD_GRUPO_CAUSA_BASICA'] = ""
#     cids['CAUSA_BASICA'] = ""
    cids['COD_CAUSA_BASICA'] = ""
    cids['CAUSA_BASICA'] = ""
    cids['CAPITULO_CAUSA_BASICA'] = ""
    cids['COD_CAPITULO_CAUSA_BASICA'] = ""
    
    df_cid_cap.apply(separando, axis='columns')
#     print(df_cid_cap.head())
    df_cid_cap.apply(capitulo_cid, cids=cids, axis='columns')
    df_cid_grupos.apply(separando, axis='columns')
    df_cid_grupos.apply(agrupamento_cid, cids=cids, axis='columns')
    df_cid_cate.apply(categoria_cid, cids=cids, axis='columns')
    df_cid_sub.apply(sub_categoria_cid, cids=cids, axis='columns')
#     ['CAPITULO_CAUSA_BASICA'], cids['COD_CAPITULO_CAUSA_BASICA'], cids['COD_GRUPO_CAUSA_BASICA'], cids['COD_CATEGORIA_CAUSA_BASICA']
    return cids

In [340]:
def cod_ocup(row, ocupacoes):
    ocupacoes.loc[(ocupacoes.OCUP.str[:6] == row.CODIGO), ['OCUPACAO']] = row.TITULO

In [341]:
def cod_group_ocup(row, ocupacoes):
    ocupacoes.loc[(ocupacoes.OCUP.str[0] == row.CODIGO), 
                  ['GRUPO_OCUPACAO', 'CODIGO_GRUPO_OCUPACAO']] = [row.TITULO, row.CODIGO]

In [342]:
def ocupacoes(df):
#     df_ocupacoes = pd.read_csv('../../Downloads/CBO2002_Ocupacao.csv', header=0, sep=';', encoding='latin1')
    df_grupo = pd.read_csv('../../Downloads/CBO2002_Grande_Grupo.csv', header=0, sep=';', encoding='latin1')
    
#     df_ocupacoes['CODIGO'] = df_ocupacoes['CODIGO'].astype('str')
    df_grupo['CODIGO'] = df_grupo['CODIGO'].astype('str')
    
    ocupacoes = pd.DataFrame(df['OCUP'].astype('str'))
#     ocupacoes['OCUPACAO'] = "" 
    ocupacoes['GRUPO_OCUPACAO'] = ""
    ocupacoes['CODIGO_GRUPO_OCUPACAO'] = ""
    
#     df_ocupacoes.apply(cod_ocup, ocupacoes=ocupacoes, axis='columns')
    df_grupo.apply(cod_group_ocup, ocupacoes=ocupacoes, axis='columns')
    ocupacoes['GRUPO_OCUPACAO'] = ocupacoes['GRUPO_OCUPACAO'].fillna('SEM OCUPAÇÃO') 
    
    return ocupacoes['GRUPO_OCUPACAO'], ocupacoes['CODIGO_GRUPO_OCUPACAO']

In [343]:
def retirando_covid(df):
    df_covid = df[df['CAUSA_BASICA'].str.contains('coronavirus') == True]
    df_covid = df_covid.drop(columns=['CAUSA_BASICA'])
    
    df_covid = df_covid.rename(columns={'assistmed': 'teve_assistencia_medica', 'racacor': 'raca_cor', 'lococor': 'local_ocorrencia',
                   'esc2010': 'escolaridade'})
    
    df_covid.to_csv('../../mortes_por_covid_2020.csv', header=True, sep=';', encoding='latin1', index=False)
    
    df_sem_covid = df[df['CAUSA_BASICA'].str.contains('coronavirus') == False]
    
    return df_sem_covid

In [344]:
def clean_dataset(df):
    df = df.loc[(df['CIRCOBITO'].isnull()) | (df['CIRCOBITO'] == 9)] # retirando as circunstância de óbito que não envolvem doença como causa
    
    
#     df['HORAOBITO'] = df['HORAOBITO'].astype('str')
#### DROP COLUMNS
    df = df.drop(columns=['contador', 'DTOBITO', 'DTNASC', 'HORAOBITO', 'CODESTAB', 'DTATESTADO', 'NUMEROLOTE', 'DTCADASTRO', 'ATESTANTE', 
                          'STCODIFICA', 'CODIFICADO', 'DTOBITO', 'DTNASC']
                )

#### CATEGORIZANDO OS SEXOS

    df['SEXO'] = df['SEXO'].replace(1, "M")
    df['SEXO'] = df['SEXO'].replace(0, "I")
    df['SEXO'] = df['SEXO'].replace(2, "F")

#### CATEGORIZANDO RAÇAS/COR

    df['RACACOR'] = df['RACACOR'].replace([1, 2, 3, 4, 5], ['BRANCA', 'PRETA', 'AMARELA', 'PARDA', 'INDIGENA'])

#### DATA DE NASCIMENTO

#     dt_nasc = clean_date(df, 'DTNASC')


#     df['DIA_NASC'] = dt_nasc['DIA']
#     df['MES_NASC'] = dt_nasc['MES']
#     df['ANO_NASC'] = dt_nasc['ANO']
    
#     df['DIA_NASC'] = df['DIA_NASC'].astype('int')
#     df['MES_NASC'] = df['MES_NASC'].astype('int')
#     df['ANO_NASC'] = df['ANO_NASC'].astype('int')

#### DATA DE ÓBITO

#     dt_obito = clean_date(df, 'DTOBITO')

#     df['DIA_OBITO'] = dt_obito['DIA'].astype('int')
#     df['MES_OBITO'] = dt_obito['MES'].astype('int')
#     df['ANO_OBITO'] = dt_obito['ANO'].astype('int')



    df = df.drop(columns=['IDADEMAE', 'ESCMAE', 'ESCMAE2010', 'OCUPMAE', 'PESO', 'ORIGEM', 'CB_PRE', 
                          'SERIESCMAE', 'GRAVIDEZ', 'GESTACAO', 'SEMAGESTAC', 'PARTO', 'OBITOPARTO', 'OBITOGRAV', 'OBITOPUERP',
                          'ESCMAEAGR1', 'ESCFALAGR1', 'FONTES', 'QTDFILVIVO', 'QTDFILMORT', 'VERSAOSIST', 'VERSAOSCB', 
                          'CODMUNRES', 'NUDIASOBCO', 'DTCADINV', 'DTCONINV', 'TPPOS', 'TPRESGINFO', 'TPMORTEOCO', 'NECROPSIA',
                          'COMUNSVOIM', 'DTINVESTIG', 'DTRECEBIM', 'CAUSAMAT', 'MORTEPARTO', 'ALTCAUSA',
                          'DTCONCASO', 'CIRURGIA', 'ACIDTRAB', 'FONTEINV', 'TIPOBITO', 'ESTCIV', 'ESC', 'SERIESCFAL', 
                          'CODMUNNATU', 'TPOBITOCOR', 'TPNIVELINV', 'NATURAL', 'EXAME', 'FONTES', 'DTCADINF', 'NUDIASOBCO', 
                          'STDONOVA', 'STDOEPIDEM', 'DTRECORIGA', 'DIFDATA','ATESTADO',
                          'LINHAA', 'LINHAB', 'LINHAC', 'LINHAD', 'LINHAII', 'CAUSABAS_O', 'FONTE',
                          'TP_ALTERA', 'CB_ALT', 'OPOR_DO', 
                          'CIRCOBITO'
#                           'FONTESINF', 'ESTABDESCR', 'NUDIASOBIN', 'NUDIASINF',
                         ]
                )
    
#### AJEITANDO IDADES
    df['IDADE'] = df['IDADE'].fillna(0)
    
#     df['IDADE'] = df['IDADE'].astype('str')

    df['IDADE'] = ajeitando_idades(df)
    
    faixa_etaria(df)
    
    df['IDADE'] = df['IDADE'].astype('int')


#### CATEGORIZANDO OS DADOS

    df['ASSISTMED'] = df['ASSISTMED'].replace([1, 2, 9], 
                                              ['SIM', 'NAO', 'I']
                                             )
    # I: ignorado

#     df['EXAME'] = df['EXAME'].replace([1, 2, 9], 
#                                       ['SIM', 'NAO', 'I']
#                                      )
    # I: ignorado
    

    df['LOCOCOR'] = df['LOCOCOR'].replace([1, 2, 3, 4, 5, 9], 
                                          ['HOSPITAL', 'OES', 'DOMICILIO', 'VIAP', 'OUTROS', 'I']
                                         )
    # OES: outros estabelecimentos de saúde
    # I: ignorado
    # VIAP: via pública

#     df['FONTE'] = df['FONTE'].replace([1, 2, 3, 4, 9], 
#                                       ['BO', 'HOSPITAL', 'FAMILIA', 'OUTRA', 'I']
#                                      )
    # BO: boletim de ocorrência
    # I: ignorado

    df['ESC2010'] = df['ESC2010'].replace([0, 1, 2, 3, 4, 5, 9], 
                                          ['SEM', 'EF_I', 'EF_II', 'EM', 'SUPERIOR_I', 'SUPERIOR_C', 'I']
                                         )
    # SEM: SEM ESCOLARIDADE
    # EF_I: ensino fundamental I
    # EF_II: ensino fundamental II
    # EM: ensino médio
    # SUPERIOR_I: superior incompleto
    # SUPERIOR_C: superior completo
    # I: ignorado

#     df['CIRCOBITO'] = df['CIRCOBITO'].replace([1, 2, 3, 4, 9], ['ACIDENTE', 'SUICIDIO', 'HOMICIDIO', 'OUTROS', 'I'])
    # I: ignorado

#### AJEITANDO OS ESTADOS
    df['ESTADO'], df['CODIGO_ESTADO'] = clean_states(df)

#### AJEITANDO CIDs
#     df['CAPITULO_CAUSA_BASICA'], df['COD_CAPITULO_CAUSA_BASICA'], df['COD_CATEGORIA_CAUSA_BASICA'], df['COD_CATEGORIA_CAUSA_BASICA'] = nomeando_cids(df)
#      = cids['GRUPO_CAUSA_BASICA']

    cids = nomeando_cids(df)
    
    df['GRUPO_CAUSA_BASICA'] = cids['GRUPO_CAUSA_BASICA']
    df['COD_GRUPO_CAUSA_BASICA'] = cids['COD_GRUPO_CAUSA_BASICA']
    df['COD_CAUSA_BASICA'] = cids['COD_CAUSA_BASICA']
    df['CAUSA_BASICA'] = cids['CAUSA_BASICA']
    df['CAPITULO_CAUSA_BASICA'] = cids['CAPITULO_CAUSA_BASICA']
    df['COD_CAPITULO_CAUSA_BASICA'] = cids['COD_CAPITULO_CAUSA_BASICA']
#     df = pd.merge(df, , how='inner')
#     df['CAUSA_BASICA'] = cids['CAUSA_BASICA']
#     df['CAUSA_BASICA'].dropna()
    df = df.drop(columns=['CAUSABAS'])
    
#### OCUPACAO DO ÓBITO
#     df['OCUP'] = df['OCUP'].astype('int')
    df['OCUP'] = df['OCUP'].astype('str')
#     ocup = ocupacoes(df)
#     df['OCUPACAO'] = ocup['OCUPACAO']
#     df['GRUPO_OCUPACAO'] = ocup['GRUPO_OCUPACAO']
    df['GRUPO_OCUPACAO'], df['CODIGO_GRUPO_OCUPACAO']  = ocupacoes(df)
    
#     df['OCUPACAO'],
    
#     df.loc[((df['OCUPACAO'].isnull()) & (df['GRUPO_OCUPACAO'].isnull())), ['GRUPO_OCUPACAO']] = 'SEM OCUPAÇÃO'
    
#     df.loc[((df['OCUPACAO'].isnull()) & (df['GRUPO_OCUPACAO'] == 'SEM OCUPAÇÃO')), ['OCUPACAO']] = 'SEM OCUPAÇÃO'
    
#     df.loc[((df['OCUPACAO'].isnull()) & (df['GRUPO_OCUPACAO'] != 'SEM OCUPAÇÃO')), ['OCUPACAO']] = 'NÃO ESPECIFICADO'
    
    df = df.drop(columns=['OCUP', 'CODMUNOCOR'])
    
#     df['COD_CAPITULO_CAUSA_BASICA'] = df['COD_CAPITULO_CAUSA_BASICA'].astype('int')
#     df['COD_GRUPO_OCUPACAO'] = df['COD_GRUPO_OCUPACAO'].astype('int')
#     df['COD_ESTADO'] = df['COD_ESTADO'].astype('int')
    
    df = retirando_covid(df)
    
    return df

In [ ]:
df = clean_dataset(df)

<ipython-input-327-a535b3bce61d>:4: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  idades['ANOS_IDADE'] = pd.Series()

In [ ]:
df.columns = df.columns.str.lower()

In [ ]:
df.dtypes

In [ ]:
df = df.rename(columns={'assistmed': 'teve_assistencia_medica', 'racacor': 'raca_cor', 'lococor': 'local_ocorrencia',
                   'esc2010': 'escolaridade'})

In [ ]:
df.isnull().sum()

In [ ]:
df.head()

In [ ]:
df[df['categoria_causa_basica'].str.contains('coronavirus') == True]

In [ ]:
df.to_csv('../../dobrano_2020_pre_preprocessado.csv', header=True, sep=';', encoding='latin1', index=False)

In [ ]:
df.shape